spring:
  application:
    name: chat-backend

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chatdb
    username: postgres
    password: test12!@

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  codec:
    max-in-memory-size: 10MB